insert into bosses(boss) VALUES ('Vale Guardian');
insert into bosses(boss) VALUES ('Gorseval The Multifarious');
insert into bosses(boss) VALUES ('Sabetha the Saboteur');
insert into bosses(boss) VALUES ('Slothasor');
insert into bosses(boss) VALUES ('Matthias Gabrel');
insert into bosses(boss) VALUES ('Keep Construct');
insert into bosses(boss) VALUES ('Xera');
insert into bosses(boss) VALUES ('Cairn the Indomitable');
insert into bosses(boss) VALUES ('Mursaat Overseer');
insert into bosses(boss) VALUES ('Samarog');
insert into bosses(boss) VALUES ('Deimos');
insert into bosses(boss) VALUES ('Soulless Horror');
insert into bosses(boss) VALUES ('Dhuum');
insert into bosses(boss) VALUES ('Conjured Amalgamate');
insert into bosses(boss) VALUES ('Twin Largos');
insert into bosses(boss) VALUES ('Qadim');
insert into bosses(boss) VALUES ('Cardinal Adina');
insert into bosses(boss) VALUES ('Cardinal Sabir');
insert into bosses(boss) VALUES ('Qadim the Peerless');