CREATE TABLE vg_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
phase1_dps INTEGER,
phase2_dps INTEGER,
phase3_dps INTEGER
);
CREATE TABLE gors_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
phase1_dps INTEGER,
phase2_dps INTEGER,
phase3_dps INTEGER
);
CREATE TABLE sab_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
phase1_dps INTEGER,
phase2_dps INTEGER,
phase3_dps INTEGER,
phase4_dps INTEGER
);
CREATE TABLE sloth_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
phase1_dps INTEGER,
phase2_dps INTEGER,
phase3_dps INTEGER,
phase4_dps INTEGER,
phase5_dps INTEGER,
phase6_dps INTEGER
);
CREATE TABLE matt_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
ice_dps INTEGER,
fire_dps INTEGER,
storm_dps INTEGER,
abomination_dps INTEGER
);
CREATE TABLE kc_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
phase1_dps INTEGER,
phase2_dps INTEGER,
phase3_dps INTEGER
);
CREATE TABLE xera_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
phase1_dps INTEGER,
phase2_dps INTEGER
);
CREATE TABLE cairn_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
full_fight_dps INTEGER
);
CREATE TABLE mo_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
_100to75 INTEGER,
_75to50 INTEGER,
_50to25 INTEGER,
_25to0 INTEGER
);
CREATE TABLE sam_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
phase1_dps INTEGER,
phase2_dps INTEGER,
phase3_dps INTEGER
);
CREATE TABLE dei_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
_100to10 INTEGER,
_10to0 INTEGER
);
CREATE TABLE sh_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
prebreakbar1_dps INTEGER,
prebreakbar2_dps INTEGER,
prebreakbar3_dps INTEGER
);
CREATE TABLE dhuum_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
main_fight_dps INTEGER,
dhuum_fight_dps INTEGER,
ritual_dps INTEGER
);
CREATE TABLE ca_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
burn1_dps INTEGER,
burn2_dps INTEGER,
burn3_dps INTEGER
);
CREATE TABLE twinlargos_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
nikare1_dps INTEGER,
kenut1_dps INTEGER,
nikare2_dps INTEGER,
kenut2_dps INTEGER,
nikare3_dps INTEGER,
kenut3_dps INTEGER
);
CREATE TABLE qadim1_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
qadim_p1_dps INTEGER,
qadim_p2_dps INTEGER,
qadim_p3_dps INTEGER
);
CREATE TABLE adina_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
phase1_dps INTEGER,
phase2_dps INTEGER,
phase3_dps INTEGER,
phase4_dps
);
CREATE TABLE sabir_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
phase1_dps INTEGER,
phase2_dps INTEGER,
phase3_dps INTEGER
);
CREATE TABLE prlqadim_dps(
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
phase1_dps INTEGER,
phase2_dps INTEGER,
phase3_dps INTEGER,
phase4_dps INTEGER,
phase5_dps INTEGER,
phase6_dps INTEGER
);