insert into professions(professions) values ('Core Guardian');
insert into professions(professions) values ('Dragonhunter');
insert into professions(professions) values ('Firebrand');
insert into professions(professions) values ('Willbender');
insert into professions(professions) values ('Core Revenant');
insert into professions(professions) values ('Herald');
insert into professions(professions) values ('Renegade');
insert into professions(professions) values ('Vindicator');
insert into professions(professions) values ('Core Warrior');
insert into professions(professions) values ('Berserker');
insert into professions(professions) values ('Spellbreaker');
insert into professions(professions) values ('Bladesworn');
insert into professions(professions) values ('Core Engineer');
insert into professions(professions) values ('Scrapper');
insert into professions(professions) values ('Holosmith');
insert into professions(professions) values ('Mechanist');
insert into professions(professions) values ('Core Ranger');
insert into professions(professions) values ('Druid');
insert into professions(professions) values ('Soulbeast');
insert into professions(professions) values ('Untamed');
insert into professions(professions) values ('Core Thief');
insert into professions(professions) values ('Daredevil');
insert into professions(professions) values ('Deadeye');
insert into professions(professions) values ('Specter');
insert into professions(professions) values ('Core Elementalist');
insert into professions(professions) values ('Tempest');
insert into professions(professions) values ('Weaver');
insert into professions(professions) values ('Catalyst');
insert into professions(professions) values ('Core Mesmer');
insert into professions(professions) values ('Chronomancer');
insert into professions(professions) values ('Mirage');
insert into professions(professions) values ('Virtuoso');
insert into professions(professions) values ('Core Necromancer');
insert into professions(professions) values ('Reaper');
insert into professions(professions) values ('Scourge');
insert into professions(professions) values ('Harbinger');